version: '3.9'

services:
<<<<<<< HEAD
  sonar: 
=======
  sonar:
>>>>>>> 714f20da48007ae408282af8fca095b81e3c6f20

    image: sonarqube:latest
    container_name: sonar
    ports:
<<<<<<< HEAD
      - 9000:9000

sonar-scanner \
  -Dsonar.projectKey=aresInfra \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.token=sqp_ed3e82cc7278bcb50a41dd3dd4e07f9196d9883a
=======
      - 9000:9000
>>>>>>> 714f20da48007ae408282af8fca095b81e3c6f20
